-- Collapses five tables into the Sleeper-shaped pair: `drafts` (one row per
-- league, the parent) and `draft_picks` (one row per slot).
--
-- Replaces: draft_settings, draft_state, draft_board, team_pick_assignments,
-- picks. Also drops leagues.draft_status, which becomes drafts.status.
--
-- WHY
--
-- draft_board and team_pick_assignments were keyed identically —
-- unique (league_id, pick_number), same cardinality, written in the same loop
-- in src/lib/draft/start.ts. docs/DATABASE.md#14-draft_board stated the
-- duplication outright: draft_board.assigned_team_id "mirrors
-- team_pick_assignments.current_owner_team_id for this pick_number — kept in
-- sync whenever a pick is traded." A hand-maintained mirror on the hottest
-- path in the app: every trade had to write two tables or the board would
-- quietly misreport who owned a pick, with nothing to catch it.
--
-- team_pick_assignments.round and .position_in_round were stored derivations —
-- pure functions of pick_number, league_size and order type, already computed
-- by src/lib/draft/order.ts. Nothing verified the stored copies.
--
-- Two invariants stop being maintained by convention and start being true by
-- construction:
--   * "traded" is no longer a status anyone has to remember to write. It is
--     team_id <> original_team_id.
--   * The pick slot and the pick made in it are one row, so they cannot
--     disagree about whether a pick happened. The old draft_board.pick_id FK
--     plus draft_board.status plus the existence of a picks row were three
--     representations of one fact.
--
-- SETTINGS ARE STORED TWICE, DELIBERATELY
--
-- drafts.settings and drafts.metadata hold Sleeper's objects verbatim; rounds
-- and pick_timer are promoted to real columns. This is the pattern leagues
-- already uses (league_settings jsonb alongside league_size, scoring_format,
-- rosters_per_team), and it exists because neither half works alone: a jsonb
-- blob cannot carry a check constraint or a not-null, and columns alone throw
-- away every field Sleeper sends that we did not anticipate — unrecoverable
-- once the league changes upstream.
--
-- THE RULE THAT KEEPS THE TWO COPIES FROM DISAGREEING:
--   The columns are authoritative. The jsonb is write-once provenance, set by
--   the import transform and never read by application logic.
-- Reading settings->>'pick_timer' instead of pick_timer reintroduces exactly
-- the mirror bug this migration removes.
--
-- Only rounds and pick_timer are promoted, because they are the only two the
-- application enforces. Team count is NOT promoted — leagues.league_size
-- already holds it and start.ts validates seats against that. Roster slot
-- counts (slots_qb, slots_rb, ...) stay jsonb-only; leagues.positions has them.

-- ============================================================================
-- Preflight
-- ============================================================================

-- draft_board and team_pick_assignments rows are pure derivations of the seat
-- assignment and are regenerated by startDraft, so losing them costs nothing.
-- Completed picks are real. Refuse rather than destroy them silently.
do $$
declare
  pick_count integer;
begin
  select count(*) into pick_count from picks;

  if pick_count > 0 then
    raise exception
      'Cannot run drafts consolidation: % completed pick(s) exist and this migration drops the picks table. Export them first (select * from picks), or delete them if they belong to a test league. draft_board and team_pick_assignments rows are regenerated by startDraft and need no export.',
      pick_count;
  end if;
end;
$$;

-- ============================================================================
-- teams.sleeper_roster_id
-- ============================================================================

-- Sleeper's slot_to_roster_id maps a draft slot to a *roster_id* — an integer
-- local to the Sleeper league, not a user id and not our uuid. Without this
-- column the map stored on drafts is unresolvable: nothing connects roster 7
-- to a teams row. teams.sleeper_user_id does not substitute, because an
-- unowned roster has no user.
alter table teams
  add column sleeper_roster_id integer;

comment on column teams.sleeper_roster_id is
  'Sleeper''s roster_id for this team. Resolves drafts.slot_to_roster_id. Null for teams created in Draft House rather than imported.';

-- ============================================================================
-- drafts
-- ============================================================================

create table drafts (
  id uuid primary key default gen_random_uuid(),

  -- One draft per league: Draft House holds the current season only. Sleeper's
  -- endpoint is plural (GET /league/<id>/drafts) because it serves prior
  -- seasons; we do not import those. The season itself is never hardcoded —
  -- fetchSleeperNflState (src/lib/sleeper/client.ts) reads /state/nfl.
  league_id uuid not null unique references leagues(id) on delete cascade,
  sleeper_draft_id text,

  -- --- Sleeper's own top-level fields -------------------------------------
  type text not null default 'snake',
  -- Sleeper's four values plus the two pre-draft stages Draft House needs.
  -- Sleeper collapses everything before the first pick into `pre_draft`, but
  -- setup (the commissioner is still configuring) and lobby (configured,
  -- waiting on the start button) are different enough that the setup flow and
  -- startDraft's mutex both key off the distinction. Import maps Sleeper's
  -- pre_draft onto 'setup'; the other three carry over unchanged.
  status text not null default 'setup',
  sport text not null default 'nfl',
  season integer not null,
  season_type text not null default 'regular',
  /** Scheduled kickoff. Sleeper sends epoch ms; the transform converts. */
  start_time timestamptz,

  /** Sleeper's settings object, verbatim. Provenance only — see header. */
  settings jsonb not null default '{}'::jsonb,
  /** Sleeper's metadata object (scoring_type, name, description), verbatim. */
  metadata jsonb not null default '{}'::jsonb,

  /** Sleeper user_id -> draft slot. Null until the order is set upstream. */
  draft_order jsonb,
  /** Draft slot -> Sleeper roster_id. Resolved via teams.sleeper_roster_id. */
  slot_to_roster_id jsonb,

  -- --- Promoted from settings, because the app enforces them ---------------
  rounds integer not null,
  -- Seconds per pick. 0 means unlimited, which is Sleeper's own convention and
  -- replaces the separate draft_settings.timer_enabled flag: "start with no
  -- timer" is pick_timer = 0, and it seeds timer_active below. One column
  -- instead of two that could contradict each other.
  pick_timer integer not null default 60,

  -- --- Draft House settings (no Sleeper equivalent) ------------------------
  allow_pick_trading boolean not null default true,
  auto_draft_enabled boolean not null default false,
  auto_draft_type text not null default 'ffc_adp',

  -- --- Live clock (was draft_state) ----------------------------------------
  -- Folded in so realtime has one row to subscribe to for the whole draft.
  -- timer_seconds is the *current pick's* countdown and is not a duplicate of
  -- pick_timer above: docs/TIMER.md has the commissioner adjusting a single
  -- pick's clock without changing the league default.
  current_pick_no integer not null default 1,
  current_round integer not null default 1,
  current_team_id uuid references teams(id) on delete set null,
  timer_seconds integer not null default 60,
  timer_active boolean not null default true,
  timer_paused boolean not null default false,
  timer_started_at timestamptz,
  timer_restarted_at timestamptz,
  timer_expired boolean not null default false,
  timer_expired_at timestamptz,
  expired_team_id uuid references teams(id) on delete set null,
  /** Sleeper's last_picked. */
  last_picked_at timestamptz,

  started_at timestamptz,
  ended_at timestamptz,
  reset_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint drafts_type_check check (type in ('snake', 'linear')),
  constraint drafts_status_check
    check (status in ('setup', 'lobby', 'drafting', 'paused', 'complete')),
  constraint drafts_rounds_check check (rounds >= 1),
  -- Deliberately only >= 0, not the >= 10 floor updateLeagueSettings applies to
  -- its form. That floor is a UI choice about what the commissioner may type in
  -- Draft House; Sleeper can send any value it likes, and the seed writes
  -- pick_timer verbatim. A database floor would reject a real league at import.
  constraint drafts_pick_timer_check check (pick_timer >= 0),
  constraint drafts_timer_seconds_check check (timer_seconds >= 0),
  constraint drafts_current_round_check check (current_round >= 1),
  constraint drafts_current_pick_no_check check (current_pick_no >= 1)
);

create trigger set_drafts_updated_at
  before update on drafts
  for each row execute function set_updated_at();

-- ============================================================================
-- draft_picks
-- ============================================================================

-- One row per slot, generated in full when the draft starts. player columns
-- are null until the pick is made — the row's existence is the slot, and the
-- player is what lands in it.
create table draft_picks (
  id uuid primary key default gen_random_uuid(),
  draft_id uuid not null references drafts(id) on delete cascade,
  -- Denormalized so the RLS policy below is a plain is_league_member() call
  -- rather than a join through drafts on every row read.
  league_id uuid not null references leagues(id) on delete cascade,

  pick_no integer not null,
  round integer not null,
  -- The seat, matching teams.draft_position. Sleeper's name for it is
  -- draft_slot, kept here for parity. NOT the place in the round's sequence —
  -- those differ on even rounds of a snake, and src/lib/draft/order.ts derives
  -- the sequence position rather than storing it.
  draft_slot integer not null,

  -- Owner now. A traded pick moves this and leaves original_team_id alone, so
  -- `team_id <> original_team_id` *is* "this pick was traded" — no status value
  -- to keep in sync.
  team_id uuid not null references teams(id) on delete cascade,
  original_team_id uuid not null references teams(id) on delete cascade,
  /** The person who submitted it. Null for auto-drafted picks. */
  picked_by uuid references users(id) on delete set null,

  status text not null default 'pending',

  sleeper_player_id text,
  player_name text,
  player_position text,
  player_nfl_team text,
  is_keeper boolean not null default false,
  picked_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint draft_picks_unique_slot unique (draft_id, pick_no),
  constraint draft_picks_pick_no_check check (pick_no >= 1),
  constraint draft_picks_round_check check (round >= 1),
  constraint draft_picks_draft_slot_check check (draft_slot >= 1),
  constraint draft_picks_status_check
    check (status in ('pending', 'expired', 'completed', 'forfeited')),
  -- Carried over from picks_unique_player_per_league. Nulls do not conflict in
  -- a Postgres unique index, so the ~200 unmade slots coexist fine while two
  -- teams still cannot draft the same player.
  constraint draft_picks_unique_player unique (league_id, sleeper_player_id),
  -- A completed pick without a player is the state the old three-way split
  -- (draft_board.status / draft_board.pick_id / picks row) could reach and
  -- nothing detected.
  constraint draft_picks_completed_has_player
    check (status <> 'completed' or sleeper_player_id is not null)
);

create trigger set_draft_picks_updated_at
  before update on draft_picks
  for each row execute function set_updated_at();

-- ============================================================================
-- Repoint the FKs that referenced picks
-- ============================================================================

-- chat_messages.pick_id and reactions.pick_id pointed at picks(id). The
-- preflight guarantees there were no picks, so there is nothing to remap.
alter table chat_messages drop constraint if exists chat_messages_pick_id_fkey;
alter table chat_messages
  add constraint chat_messages_pick_id_fkey
  foreign key (pick_id) references draft_picks(id) on delete set null;

alter table reactions drop constraint if exists reactions_pick_id_fkey;
alter table reactions
  add constraint reactions_pick_id_fkey
  foreign key (pick_id) references draft_picks(id) on delete cascade;

-- reactions_select (20260823000003_rls_policies.sql) reads through picks to
-- reach a league_id. That is a hard dependency — `drop table picks` fails with
-- a 2BP01 while this policy exists — so it is replaced here rather than left
-- for the drop to trip over. draft_picks carries league_id directly, so the
-- rewritten policy is the same shape against the new table.
drop policy reactions_select on reactions;
create policy reactions_select on reactions for select using (
  exists (
    select 1 from draft_picks
    where draft_picks.id = reactions.pick_id
      and is_league_member(draft_picks.league_id)
  )
);

-- draft_reset_archive.archived_picks stays untyped jsonb and now carries
-- draft_picks rows. Deliberately unconstrained: it is the crash-recovery dump,
-- and a constraint that can reject a recovery payload is worse than useless at
-- the moment it is needed.

-- ============================================================================
-- Drop the replaced tables
-- ============================================================================

drop table team_pick_assignments;
drop table draft_board;
drop table picks;
drop table draft_state;
drop table draft_settings;

-- leagues.draft_status becomes drafts.status. Keeping both would recreate the
-- two-sources-of-truth problem this migration exists to remove: the import
-- creates the drafts row in 'setup', so the status always exists and there
-- is no window where a league has no draft state.
-- Drops idx_leagues_draft_status (20260823000002_indexes.sql) with it, which is
-- why that index is not dropped explicitly above.
alter table leagues drop column draft_status;

-- Same reasoning, two more columns: draft_format is drafts.type and
-- draft_start_time is drafts.start_time. Leaving them would keep the settings
-- form writing the draft's configuration to two tables with no transaction
-- spanning them — which updateDraftSettings already had to apologize for in a
-- comment, because the first write can land while the second does not.
alter table leagues drop column draft_format;
alter table leagues drop column draft_start_time;

-- ============================================================================
-- Indexes
-- ============================================================================

-- league_id is already indexed by its unique constraint.
create index idx_drafts_status on drafts(status);
create index idx_drafts_current_team on drafts(current_team_id);

-- (draft_id, pick_no) is covered by draft_picks_unique_slot.
create index idx_draft_picks_league_id on draft_picks(league_id);
create index idx_draft_picks_team on draft_picks(league_id, team_id);
create index idx_draft_picks_original_team on draft_picks(league_id, original_team_id);
create index idx_draft_picks_status on draft_picks(league_id, status);

-- ============================================================================
-- RLS
-- ============================================================================

alter table drafts enable row level security;
alter table draft_picks enable row level security;

create policy drafts_select on drafts
  for select using (is_league_member(league_id));

create policy draft_picks_select on draft_picks
  for select using (is_league_member(league_id));

-- draft_picks stays select-only for clients, per docs/SECURITY.md — every
-- write goes through the service role in server actions. That is the rule that
-- actually prevents pick manipulation.
--
-- drafts is the one exception, and it is a narrow one. startDraft's mutex is a
-- guarded update — two commissioners clicking at once, only the one whose
-- update still matches status = 'lobby' wins — and it needs RLS to be the
-- authorization check with teeth. Same shape as draft_settings_update, which
-- this replaces.
create policy drafts_update on drafts
  for update using (is_commissioner(league_id));

-- RLS restricts which ROWS the commissioner may update; it cannot restrict
-- which columns. Without this grant, the policy above would also let a
-- commissioner set current_pick_no or timer_seconds straight from the browser
-- and skip the draft engine entirely. Column privileges are the mechanism that
-- closes that, so the writable set is enumerated explicitly: the pre-draft
-- settings form plus the status transition.
revoke update on drafts from authenticated;
grant update (
  type,
  status,
  start_time,
  pick_timer,
  allow_pick_trading,
  auto_draft_enabled,
  auto_draft_type
) on drafts to authenticated;

-- Adding a commissioner-editable setting to drafts is a two-place change: the
-- column, and this grant. A new column is NOT writable by the settings form
-- until it is listed here — the failure is a permission error on save, not a
-- silent no-op.
